kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus
  namespace: monitoring
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-storageclass
  volumeMode: Filesystem
  capacity:
    storage: 10Gi